# Generated by Django 6.0.4 on 2026-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('organizations', '0002_alter_organization_logo'),
        ('tables', '0001_initial'),
        ('users', '0002_alter_userprofile_organization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', 'status'], name='order_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['organization', '-created_at'], name='order_org_created_idx'),
        ),
    ]
