# Generated by Django 6.0.4 on 2026-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_menu_image_url'),
        ('organizations', '0002_alter_organization_logo'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['organization', 'is_available', 'sort_order'], name='menu_org_avail_sort_idx'),
        ),
    ]
