# Generated by Django 6.0.4 on 2026-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_order_org_status_idx_and_more'),
        ('organizations', '0002_alter_organization_logo'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'payment_status'], name='payment_org_status_idx'),
        ),
    ]
