# Generated by Django 6.0.4 on 2026-06-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0001_initial'),
        ('organizations', '0002_alter_organization_logo'),
        ('users', '0002_alter_userprofile_organization'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recipient_read_idx'),
        ),
    ]
